### ISSUE TITLE
Handle error when config.checks is undefined

### ISSUE THREAD

**Issue by adslaton** [cnnlabs/cnn-health#4]
# Error

```
/Users/adslaton/dev/we/cnn-hapi/node_modules/cnn-health/lib/healthchecks.js:8
        this.checks = config.checks.map((check) => {
                                   ^

TypeError: Cannot read property 'map' of undefined
    at new HealthChecks (/Users/adslaton/dev/we/cnn-hapi/node_modules/cnn-health/lib/healthchecks.js:8:36)
    at startup (/Users/adslaton/dev/we/cnn-hapi/node_modules/cnn-health/lib/startup.js:12:24)
    at module.exports (/Users/adslaton/dev/we/cnn-hapi/node_modules/cnn-health/main.js:19:26)
    at Object.<anonymous> (/Users/adslaton/dev/we/cnn-hapi/example/app.js:15:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
```

**Comment by adslaton** [comment]
Resolved
